package com.mycompany.trabalhosub.panel;

import com.mycompany.trabalhosub.dto.FilmeDto;
import com.mycompany.trabalhosub.models.FilmeAssistido;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import services.FilmeService;

public class Inicial extends javax.swing.JFrame {

    
    
    private FilmeService filmeService;
    private FilmeDto filmeDto;
    private SelecionaFilmeView selecionaFilmeView;
 
   private static final String LOG_DIRECTORY = "Log";
    private static final String LOG_FILE_NAME = "filmes_assistidos.csv";
    private static final File logFile = new File(LOG_DIRECTORY, LOG_FILE_NAME);
    
 
    
   FilmeDto filmeInsercao = new FilmeDto();
   DefaultTableModel defaultTableModel = new DefaultTableModel(new Object[]{"Nome"}, 0);
    public Inicial() {
        initComponents();
        

    }

 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomeCliente1 = new javax.swing.JTextField();
        btSelecionarCliente = new javax.swing.JButton();
        btSelecionarCliente1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCancelar = new javax.swing.JButton();
        JpanelFav = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        txtNomeCliente1.setBackground(new java.awt.Color(204, 204, 204));
        txtNomeCliente1.setToolTipText("");
        txtNomeCliente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNomeCliente1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNomeCliente1.setEnabled(false);
        txtNomeCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCliente1ActionPerformed(evt);
            }
        });

        btSelecionarCliente.setBackground(new java.awt.Color(0, 102, 0));
        btSelecionarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSelecionarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btSelecionarCliente.setText("PESQUISE SEU FILME AQUI");
        btSelecionarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSelecionarCliente.setName("btSelecionar"); // NOI18N
        btSelecionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarClienteActionPerformed(evt);
            }
        });

        btSelecionarCliente1.setBackground(new java.awt.Color(0, 102, 0));
        btSelecionarCliente1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSelecionarCliente1.setForeground(new java.awt.Color(255, 255, 255));
        btSelecionarCliente1.setText("VER FILMES ASISTIDOS ");
        btSelecionarCliente1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btSelecionarCliente1.setName("btSelecionar"); // NOI18N
        btSelecionarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarCliente1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(0, 102, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FILMES ASSISTIDOS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );

        btCancelar.setBackground(new java.awt.Color(255, 91, 91));
        btCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btCancelar.setText("ENCERRAR");
        btCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        JpanelFav.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JpanelFav)
                    .addComponent(btSelecionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeCliente1)
                    .addComponent(btSelecionarCliente1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btSelecionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSelecionarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelFav, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.getAccessibleContext().setAccessibleParent(jPanel8);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCliente1ActionPerformed

    }//GEN-LAST:event_txtNomeCliente1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       if (filmeInsercao.Title != null) {
            txtNomeCliente1.setText(filmeInsercao.Title);
        }
    }//GEN-LAST:event_formWindowGainedFocus

    private void btSelecionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarClienteActionPerformed
    new SelecionaFilmeView().setVisible(true);        
    }//GEN-LAST:event_btSelecionarClienteActionPerformed

    private void btSelecionarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarCliente1ActionPerformed
        String texto = txtNomeCliente1.getText();
        defaultTableModel.addRow(new Object[]{texto});
//     JFileChooser fileChooser = new JFileChooser();
//        
//        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
//        fileChooser.setAcceptAllFileFilterUsed(false); //não exibe .ALL
//        fileChooser.setFileFilter(
//                new FileNameExtensionFilter("CSV Files", "csv"));
//        
//        int returnValue = fileChooser.showOpenDialog(this);
//        
//        if(returnValue == JFileChooser.APPROVE_OPTION) {
                      File arquivo = new File("C:/Users/renat/Videos/trabalhoFrabelFilmes-main/trabalhoSub/Log/filmes_assistidos.csv");

            jTextArea1.setText(arquivo.getAbsolutePath());
            
            converterPessoa(arquivo);
//        } else {    
//            jTextArea1.setText("");
          

    }//GEN-LAST:event_btSelecionarCliente1ActionPerformed
    
    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

        private  void converterPessoa(File arquivo1) {
            
            File arquivo = new File("C:/Users/renat/Videos/trabalhoFrabelFilmes-main/trabalhoSub/Log/filmes_assistidos.csv");
            

        try (BufferedReader br = 
                new BufferedReader(new InputStreamReader(
                        new FileInputStream(arquivo.getAbsolutePath()), 
                        "UTF-8"))) {

            String linha;
            Integer id = 1;
            List<FilmeAssistido> filmeList = new ArrayList<>();
          
            br.readLine();
            while ((linha = br.readLine()) != null) {
                String[] campos = linha.split(";");
                
                FilmeAssistido filme = new FilmeAssistido();
              
                filme.setId(id++);
                filme.setNome(campos[0]);
                
                filmeList.add(filme);
                
//                PessoaDAO dao = new PessoaDAO();
//                dao.insert(pessoa);
//                
            }
            
             
            for (FilmeAssistido filme : filmeList) {
                jTextArea1.append(filme.toString());
            }
            
        } catch (IOException ex) {
            System.err.println("Algo deu errado..." + ex.getMessage());
        }
  }
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JpanelFav;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSelecionarCliente;
    private javax.swing.JButton btSelecionarCliente1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtNomeCliente1;
    // End of variables declaration//GEN-END:variables
}
